language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-scikits-learn

script: nosetests pattern_recognition/test

deploy:
  provider: heroku
  app:
    master: neural-net
  api_key: b3f1822f-cc5b-459f-a7d6-d13ded0db51d
  run:
    - "config:set BUILDPACK_URL=https://github.com/dbrgn/heroku-buildpack-python-sklearn/"

